---

# --- installing latest nginx ---
- name: Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest
  
- name: create certs directory
  file: 
    path: "/etc/pki/nginx"
    state: directory
    owner: root
    group: root
    mode: 0700

# --- copy server cert file in place
- name: Copy server cert file to /etc/pki/nginx
  template:
    src: ../../secrets/server.crt
    dest: "/etc/pki/nginx"
    owner: root
    group: root
    mode: 0600

- name: create certs private directory
  file: 
    path: "/etc/pki/nginx/private"
    state: directory
    owner: root
    group: root
    mode: 0700

# --- copy server key file in place ---
- name: Copy server key file to /etc/pki/nginx/private
  template:
    src: ../../secrets/server.key
    dest: "/etc/pki/nginx/private"
    owner: root
    group: root
    mode: 0600

# --- copy nginx.conf in place
- name: copy nginx.conf in place
  template:
    src: ../../secrets/nginx.conf
    dest: "/etc/nginx"
    owner: root
    group: root
    mode: 0644

# --- start nginx ---
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started

# --- populate /etc/hosts --- ?????
# - name: "Build hosts file"
#   lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item]['ansible_ssh_host'] }} {{item}}" state=present
#   when: hostvars[item]['ansible_ssh_host'] is defined
#   with_items: groups['all']

- name: Copy plugins.txt
  template:
    src: ../../templates/plugins.txt.j2
    dest: /tmp/plugins.txt
    owner: jenkins
    group: jenkins
    mode: 0644
    backup: true

- name: download jenkins.repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: import jenkins key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: import another key 
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

# -------------- Jenkins actually ------------------
- name: install jenkins
  yum:
    name: jenkins
    state: present

- name: Enable service jenkins
  ansible.builtin.service:
    name: jenkins
    enabled: yes
      
- name: create tmp directory
  file: 
    path: "{{ JENKINS_HOME }}/tmp"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

# --- copy jenkins config file for JCAC ---
- name: Copy Jenkins autoconfig file to {{ JENKINS_HOME }}
  template:
    src: ../../templates/jenkins.yaml.j2
    dest: "{{ JENKINS_HOME }}/jenkins.yaml"
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Enable Jenkins-CI auto-config
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ".*-Djava.awt.headless=true.*"
    line: 'JENKINS_JAVA_OPTIONS="-Djenkins.install.runSetupWizard=false -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir={{ JENKINS_HOME }}/tmp/ -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Moscow -Duser.timezone=Europe/Moscow"'

- name: change Jenkins-CI JAVA_ARGS
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JAVA_ARGS=
    line: 'JAVA_ARGS="-Dpermissive-script-security.enabled=true"'
  notify: Restart Jenkins
  tags:
    - jenkins-conf

# ----- Jenkins plugins manager -----
- name: Get the plugins manager
  shell: curl -L -X GET "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.11.1/jenkins-plugin-manager-2.11.1.jar" \
              -o jenkins-plugin-manager.jar

- name: install plugins
  shell: |
    cd /home/devops
    java -jar jenkins-plugin-manager.jar -w /usr/lib/jenkins/jenkins.war -d {{ JENKINS_HOME }}/plugins -f /tmp/plugins.txt
    chown -R jenkins:jenkins {{ JENKINS_HOME }}/plugins

- name: remove jenkins-plugin-manager
  file: 
    path: /home/devops/jenkins-plugin-manager.jar
    state: absent

- name: create secrets directory
  file: 
    path: "{{ JENKINS_HOME }}/secrets"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0700

- name: start jenkins
  systemd:
    name: jenkins
    state: started

- name: sleep for 10 seconds and continue with play
  pause:
    seconds: 10

- name: Copy private key 
  template:
    src: ../../secrets/ssh-agent-access-key
    dest: /home/jenkins/.ssh/id_rsa
    owner: jenkins
    group: jenkins
    mode: 0600

- name: Copy github token
  template:
    src: ../../secrets/github-token
    dest: "{{ JENKINS_SECRETS }}/github-token"
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Copy slack token
  template:
    src: ../../secrets/slack-token
    dest: "{{ JENKINS_SECRETS }}/slack-token"
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Copy agents ssh key 
  template:
    src: ../../secrets/ssh-agent-access-key
    dest: "{{ JENKINS_SECRETS }}/ssh-agent-access-key"
    owner: jenkins
    group: jenkins
    mode: 0644
    
- name: Copy vault role id 
  template:
    src: ../../secrets/vault-role-id
    dest: "{{ JENKINS_SECRETS }}/vault-role-id"
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Copy vault secret id 
  template:
    src: ../../secrets/vault-secret-id
    dest: "{{ JENKINS_SECRETS }}/vault-secret-id"
    owner: jenkins
    group: jenkins
    mode: 0644


- name: Copy agents ssh key 
  template:
    src: ../../secrets/deploy-key
    dest: "{{ JENKINS_SECRETS }}/deploy-key"
    owner: jenkins
    group: jenkins
    mode: 0644
