---

# - name: Wait for jenkins master
#   wait_for:
#     host: "{{ groups['ci'][0] }}"
#     port: 443
#     sleep: 10    
#     timeout: 300 

#- name: download agent.jar
#  get_url:
#    url: http://{{ groups['ci'][0] }}:8080/jnlpJars/agent.jar
#    dest: /home/jenkins

#- name: run agent on the host
#  shell: java -jar /home/jenkins/agent.jar -jnlpUrl http://{{ groups['ci'][0] }}:8080/computer/agent{{ groups['ciagents'].index(inventory_hostname)+1 }}/jenkins-agent.jnlp &
