---

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: remove firewalld
  package:
    name: firewalld
    state: absent

- name: install openjdk
  yum:
    name: java-11-openjdk-devel
    state: present

# add docker ?